package com.xiepanpan.ecps.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-11-18T20:08:31.855+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://service.ws.ecps.xiepanpan.com/", name = "EbWSItemService")
@XmlSeeAlso({ObjectFactory.class})
public interface EbWSItemService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "publishItem", targetNamespace = "http://service.ws.ecps.xiepanpan.com/", className = "com.xiepanpan.ecps.stub.PublishItem")
    @WebMethod
    @ResponseWrapper(localName = "publishItemResponse", targetNamespace = "http://service.ws.ecps.xiepanpan.com/", className = "com.xiepanpan.ecps.stub.PublishItemResponse")
    public String publishItem(
            @WebParam(name = "arg0", targetNamespace = "")
                    Long arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );
}
