package com.xiepanpan.ecps.model;

import java.util.Date;

public class EbConsoleLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_CONSOLE_LOG.CONSOLE_LOG_ID
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	private Long consoleLogId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_CONSOLE_LOG.ENTITY_NAME
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	private String entityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_CONSOLE_LOG.ENTITY_ID
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	private Long entityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_CONSOLE_LOG.USER_ID
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_CONSOLE_LOG.OP_TYPE
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	private String opType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_CONSOLE_LOG.OP_TIME
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	private Date opTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_CONSOLE_LOG.NOTES
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	private String notes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_CONSOLE_LOG.TABLE_NAME
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	private String tableName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_CONSOLE_LOG.CONSOLE_LOG_ID
	 * @return  the value of EB_CONSOLE_LOG.CONSOLE_LOG_ID
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public Long getConsoleLogId() {
		return consoleLogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_CONSOLE_LOG.CONSOLE_LOG_ID
	 * @param consoleLogId  the value for EB_CONSOLE_LOG.CONSOLE_LOG_ID
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public void setConsoleLogId(Long consoleLogId) {
		this.consoleLogId = consoleLogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_CONSOLE_LOG.ENTITY_NAME
	 * @return  the value of EB_CONSOLE_LOG.ENTITY_NAME
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public String getEntityName() {
		return entityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_CONSOLE_LOG.ENTITY_NAME
	 * @param entityName  the value for EB_CONSOLE_LOG.ENTITY_NAME
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_CONSOLE_LOG.ENTITY_ID
	 * @return  the value of EB_CONSOLE_LOG.ENTITY_ID
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public Long getEntityId() {
		return entityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_CONSOLE_LOG.ENTITY_ID
	 * @param entityId  the value for EB_CONSOLE_LOG.ENTITY_ID
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public void setEntityId(Long entityId) {
		this.entityId = entityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_CONSOLE_LOG.USER_ID
	 * @return  the value of EB_CONSOLE_LOG.USER_ID
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_CONSOLE_LOG.USER_ID
	 * @param userId  the value for EB_CONSOLE_LOG.USER_ID
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_CONSOLE_LOG.OP_TYPE
	 * @return  the value of EB_CONSOLE_LOG.OP_TYPE
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public String getOpType() {
		return opType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_CONSOLE_LOG.OP_TYPE
	 * @param opType  the value for EB_CONSOLE_LOG.OP_TYPE
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public void setOpType(String opType) {
		this.opType = opType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_CONSOLE_LOG.OP_TIME
	 * @return  the value of EB_CONSOLE_LOG.OP_TIME
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public Date getOpTime() {
		return opTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_CONSOLE_LOG.OP_TIME
	 * @param opTime  the value for EB_CONSOLE_LOG.OP_TIME
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public void setOpTime(Date opTime) {
		this.opTime = opTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_CONSOLE_LOG.NOTES
	 * @return  the value of EB_CONSOLE_LOG.NOTES
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_CONSOLE_LOG.NOTES
	 * @param notes  the value for EB_CONSOLE_LOG.NOTES
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_CONSOLE_LOG.TABLE_NAME
	 * @return  the value of EB_CONSOLE_LOG.TABLE_NAME
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public String getTableName() {
		return tableName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_CONSOLE_LOG.TABLE_NAME
	 * @param tableName  the value for EB_CONSOLE_LOG.TABLE_NAME
	 * @mbggenerated  Sat Jul 25 09:47:02 CST 2015
	 */
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}
}