package com.xiepanpan.ecps.model;

/**
 * 商品大字段实体类
 */
public class EbItemClob {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ITEM_CLOB.ITEM_ID
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ITEM_CLOB.ITEM_DESC
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    private String itemDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ITEM_CLOB.PACKING_LIST
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    private String packingList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ITEM_CLOB.ITEM_ID
     *
     * @return the value of EB_ITEM_CLOB.ITEM_ID
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ITEM_CLOB.ITEM_ID
     *
     * @param itemId the value for EB_ITEM_CLOB.ITEM_ID
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ITEM_CLOB.ITEM_DESC
     *
     * @return the value of EB_ITEM_CLOB.ITEM_DESC
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ITEM_CLOB.ITEM_DESC
     *
     * @param itemDesc the value for EB_ITEM_CLOB.ITEM_DESC
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ITEM_CLOB.PACKING_LIST
     *
     * @return the value of EB_ITEM_CLOB.PACKING_LIST
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public String getPackingList() {
        return packingList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ITEM_CLOB.PACKING_LIST
     *
     * @param packingList the value for EB_ITEM_CLOB.PACKING_LIST
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public void setPackingList(String packingList) {
        this.packingList = packingList;
    }
}