package com.xiepanpan.ecps.model;

import java.math.BigDecimal;

public class EbOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.ORDER_DETAIL_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Long orderDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.ORDER_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.ITEM_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.ITEM_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.ITEM_NO
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.SKU_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Long skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.SKU
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.SKU_IMG
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String skuImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.SKU_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String skuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.SKU_CAT_TYPE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Integer skuCatType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.SKU_SPEC
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String skuSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.MARKET_PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.SKU_DISCOUNT
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private BigDecimal skuDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.SKU_PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private BigDecimal skuPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.OFFER_GROUP_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Long offerGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.OFFER_GROUP_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String offerGroupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.OFFER_TYPE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Short offerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.SHORT_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.OFFER_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Long offerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.OFFER_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String offerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.OFFER_NO
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String offerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.SHORT_NAME2
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String shortName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.OFFER_TERM
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Short offerTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.COMMIT_MONTHLY
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private BigDecimal commitMonthly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.PREPAID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private BigDecimal prepaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.PERIOD
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Short period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.REFUND_MONTHLY
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private BigDecimal refundMonthly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.REFUND_1ST_MONTH
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private BigDecimal refund1stMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.REFUND_LAST_MONTH
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private BigDecimal refundLastMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.ORDER_DETAIL_TYPE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Short orderDetailType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.MERCHANT_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.QUANTITY
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.SERIESCODE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String seriescode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.OFFER_GROUP_NO
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String offerGroupNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.PROMO_TYPE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Short promoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.COND_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String condId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.PRODUCT_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.PAYMENT_PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private BigDecimal paymentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.PURCHASE_PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private BigDecimal purchasePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.SIMCARD_SUIT_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private Long simcardSuitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER_DETAIL.SIMCARD_PACKAGE_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    private String simcardPackageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.ORDER_DETAIL_ID
     *
     * @return the value of EB_ORDER_DETAIL.ORDER_DETAIL_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Long getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.ORDER_DETAIL_ID
     *
     * @param orderDetailId the value for EB_ORDER_DETAIL.ORDER_DETAIL_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setOrderDetailId(Long orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.ORDER_ID
     *
     * @return the value of EB_ORDER_DETAIL.ORDER_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.ORDER_ID
     *
     * @param orderId the value for EB_ORDER_DETAIL.ORDER_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.ITEM_ID
     *
     * @return the value of EB_ORDER_DETAIL.ITEM_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.ITEM_ID
     *
     * @param itemId the value for EB_ORDER_DETAIL.ITEM_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.ITEM_NAME
     *
     * @return the value of EB_ORDER_DETAIL.ITEM_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.ITEM_NAME
     *
     * @param itemName the value for EB_ORDER_DETAIL.ITEM_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.ITEM_NO
     *
     * @return the value of EB_ORDER_DETAIL.ITEM_NO
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.ITEM_NO
     *
     * @param itemNo the value for EB_ORDER_DETAIL.ITEM_NO
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.SKU_ID
     *
     * @return the value of EB_ORDER_DETAIL.SKU_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.SKU_ID
     *
     * @param skuId the value for EB_ORDER_DETAIL.SKU_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.SKU
     *
     * @return the value of EB_ORDER_DETAIL.SKU
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.SKU
     *
     * @param sku the value for EB_ORDER_DETAIL.SKU
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setSku(String sku) {
        this.sku = sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.SKU_IMG
     *
     * @return the value of EB_ORDER_DETAIL.SKU_IMG
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getSkuImg() {
        return skuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.SKU_IMG
     *
     * @param skuImg the value for EB_ORDER_DETAIL.SKU_IMG
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setSkuImg(String skuImg) {
        this.skuImg = skuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.SKU_NAME
     *
     * @return the value of EB_ORDER_DETAIL.SKU_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.SKU_NAME
     *
     * @param skuName the value for EB_ORDER_DETAIL.SKU_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.SKU_CAT_TYPE
     *
     * @return the value of EB_ORDER_DETAIL.SKU_CAT_TYPE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Integer getSkuCatType() {
        return skuCatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.SKU_CAT_TYPE
     *
     * @param skuCatType the value for EB_ORDER_DETAIL.SKU_CAT_TYPE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setSkuCatType(Integer skuCatType) {
        this.skuCatType = skuCatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.SKU_SPEC
     *
     * @return the value of EB_ORDER_DETAIL.SKU_SPEC
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getSkuSpec() {
        return skuSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.SKU_SPEC
     *
     * @param skuSpec the value for EB_ORDER_DETAIL.SKU_SPEC
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setSkuSpec(String skuSpec) {
        this.skuSpec = skuSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.MARKET_PRICE
     *
     * @return the value of EB_ORDER_DETAIL.MARKET_PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.MARKET_PRICE
     *
     * @param marketPrice the value for EB_ORDER_DETAIL.MARKET_PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.SKU_DISCOUNT
     *
     * @return the value of EB_ORDER_DETAIL.SKU_DISCOUNT
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public BigDecimal getSkuDiscount() {
        return skuDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.SKU_DISCOUNT
     *
     * @param skuDiscount the value for EB_ORDER_DETAIL.SKU_DISCOUNT
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setSkuDiscount(BigDecimal skuDiscount) {
        this.skuDiscount = skuDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.SKU_PRICE
     *
     * @return the value of EB_ORDER_DETAIL.SKU_PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public BigDecimal getSkuPrice() {
        return skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.SKU_PRICE
     *
     * @param skuPrice the value for EB_ORDER_DETAIL.SKU_PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setSkuPrice(BigDecimal skuPrice) {
        this.skuPrice = skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.OFFER_GROUP_ID
     *
     * @return the value of EB_ORDER_DETAIL.OFFER_GROUP_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Long getOfferGroupId() {
        return offerGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.OFFER_GROUP_ID
     *
     * @param offerGroupId the value for EB_ORDER_DETAIL.OFFER_GROUP_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setOfferGroupId(Long offerGroupId) {
        this.offerGroupId = offerGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.OFFER_GROUP_NAME
     *
     * @return the value of EB_ORDER_DETAIL.OFFER_GROUP_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getOfferGroupName() {
        return offerGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.OFFER_GROUP_NAME
     *
     * @param offerGroupName the value for EB_ORDER_DETAIL.OFFER_GROUP_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setOfferGroupName(String offerGroupName) {
        this.offerGroupName = offerGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.OFFER_TYPE
     *
     * @return the value of EB_ORDER_DETAIL.OFFER_TYPE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Short getOfferType() {
        return offerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.OFFER_TYPE
     *
     * @param offerType the value for EB_ORDER_DETAIL.OFFER_TYPE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setOfferType(Short offerType) {
        this.offerType = offerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.SHORT_NAME
     *
     * @return the value of EB_ORDER_DETAIL.SHORT_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.SHORT_NAME
     *
     * @param shortName the value for EB_ORDER_DETAIL.SHORT_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.OFFER_ID
     *
     * @return the value of EB_ORDER_DETAIL.OFFER_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Long getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.OFFER_ID
     *
     * @param offerId the value for EB_ORDER_DETAIL.OFFER_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setOfferId(Long offerId) {
        this.offerId = offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.OFFER_NAME
     *
     * @return the value of EB_ORDER_DETAIL.OFFER_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getOfferName() {
        return offerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.OFFER_NAME
     *
     * @param offerName the value for EB_ORDER_DETAIL.OFFER_NAME
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setOfferName(String offerName) {
        this.offerName = offerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.OFFER_NO
     *
     * @return the value of EB_ORDER_DETAIL.OFFER_NO
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getOfferNo() {
        return offerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.OFFER_NO
     *
     * @param offerNo the value for EB_ORDER_DETAIL.OFFER_NO
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setOfferNo(String offerNo) {
        this.offerNo = offerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.SHORT_NAME2
     *
     * @return the value of EB_ORDER_DETAIL.SHORT_NAME2
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getShortName2() {
        return shortName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.SHORT_NAME2
     *
     * @param shortName2 the value for EB_ORDER_DETAIL.SHORT_NAME2
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setShortName2(String shortName2) {
        this.shortName2 = shortName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.OFFER_TERM
     *
     * @return the value of EB_ORDER_DETAIL.OFFER_TERM
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Short getOfferTerm() {
        return offerTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.OFFER_TERM
     *
     * @param offerTerm the value for EB_ORDER_DETAIL.OFFER_TERM
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setOfferTerm(Short offerTerm) {
        this.offerTerm = offerTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.COMMIT_MONTHLY
     *
     * @return the value of EB_ORDER_DETAIL.COMMIT_MONTHLY
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public BigDecimal getCommitMonthly() {
        return commitMonthly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.COMMIT_MONTHLY
     *
     * @param commitMonthly the value for EB_ORDER_DETAIL.COMMIT_MONTHLY
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setCommitMonthly(BigDecimal commitMonthly) {
        this.commitMonthly = commitMonthly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.PREPAID
     *
     * @return the value of EB_ORDER_DETAIL.PREPAID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public BigDecimal getPrepaid() {
        return prepaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.PREPAID
     *
     * @param prepaid the value for EB_ORDER_DETAIL.PREPAID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setPrepaid(BigDecimal prepaid) {
        this.prepaid = prepaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.PERIOD
     *
     * @return the value of EB_ORDER_DETAIL.PERIOD
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Short getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.PERIOD
     *
     * @param period the value for EB_ORDER_DETAIL.PERIOD
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setPeriod(Short period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.REFUND_MONTHLY
     *
     * @return the value of EB_ORDER_DETAIL.REFUND_MONTHLY
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public BigDecimal getRefundMonthly() {
        return refundMonthly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.REFUND_MONTHLY
     *
     * @param refundMonthly the value for EB_ORDER_DETAIL.REFUND_MONTHLY
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setRefundMonthly(BigDecimal refundMonthly) {
        this.refundMonthly = refundMonthly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.REFUND_1ST_MONTH
     *
     * @return the value of EB_ORDER_DETAIL.REFUND_1ST_MONTH
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public BigDecimal getRefund1stMonth() {
        return refund1stMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.REFUND_1ST_MONTH
     *
     * @param refund1stMonth the value for EB_ORDER_DETAIL.REFUND_1ST_MONTH
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setRefund1stMonth(BigDecimal refund1stMonth) {
        this.refund1stMonth = refund1stMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.REFUND_LAST_MONTH
     *
     * @return the value of EB_ORDER_DETAIL.REFUND_LAST_MONTH
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public BigDecimal getRefundLastMonth() {
        return refundLastMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.REFUND_LAST_MONTH
     *
     * @param refundLastMonth the value for EB_ORDER_DETAIL.REFUND_LAST_MONTH
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setRefundLastMonth(BigDecimal refundLastMonth) {
        this.refundLastMonth = refundLastMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.ORDER_DETAIL_TYPE
     *
     * @return the value of EB_ORDER_DETAIL.ORDER_DETAIL_TYPE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Short getOrderDetailType() {
        return orderDetailType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.ORDER_DETAIL_TYPE
     *
     * @param orderDetailType the value for EB_ORDER_DETAIL.ORDER_DETAIL_TYPE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setOrderDetailType(Short orderDetailType) {
        this.orderDetailType = orderDetailType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.MERCHANT_ID
     *
     * @return the value of EB_ORDER_DETAIL.MERCHANT_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.MERCHANT_ID
     *
     * @param merchantId the value for EB_ORDER_DETAIL.MERCHANT_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.QUANTITY
     *
     * @return the value of EB_ORDER_DETAIL.QUANTITY
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.QUANTITY
     *
     * @param quantity the value for EB_ORDER_DETAIL.QUANTITY
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.PRICE
     *
     * @return the value of EB_ORDER_DETAIL.PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.PRICE
     *
     * @param price the value for EB_ORDER_DETAIL.PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.SERIESCODE
     *
     * @return the value of EB_ORDER_DETAIL.SERIESCODE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getSeriescode() {
        return seriescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.SERIESCODE
     *
     * @param seriescode the value for EB_ORDER_DETAIL.SERIESCODE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setSeriescode(String seriescode) {
        this.seriescode = seriescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.OFFER_GROUP_NO
     *
     * @return the value of EB_ORDER_DETAIL.OFFER_GROUP_NO
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getOfferGroupNo() {
        return offerGroupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.OFFER_GROUP_NO
     *
     * @param offerGroupNo the value for EB_ORDER_DETAIL.OFFER_GROUP_NO
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setOfferGroupNo(String offerGroupNo) {
        this.offerGroupNo = offerGroupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.PROMO_TYPE
     *
     * @return the value of EB_ORDER_DETAIL.PROMO_TYPE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Short getPromoType() {
        return promoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.PROMO_TYPE
     *
     * @param promoType the value for EB_ORDER_DETAIL.PROMO_TYPE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setPromoType(Short promoType) {
        this.promoType = promoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.COND_ID
     *
     * @return the value of EB_ORDER_DETAIL.COND_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getCondId() {
        return condId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.COND_ID
     *
     * @param condId the value for EB_ORDER_DETAIL.COND_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setCondId(String condId) {
        this.condId = condId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.PRODUCT_ID
     *
     * @return the value of EB_ORDER_DETAIL.PRODUCT_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.PRODUCT_ID
     *
     * @param productId the value for EB_ORDER_DETAIL.PRODUCT_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.PAYMENT_PRICE
     *
     * @return the value of EB_ORDER_DETAIL.PAYMENT_PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public BigDecimal getPaymentPrice() {
        return paymentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.PAYMENT_PRICE
     *
     * @param paymentPrice the value for EB_ORDER_DETAIL.PAYMENT_PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setPaymentPrice(BigDecimal paymentPrice) {
        this.paymentPrice = paymentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.PURCHASE_PRICE
     *
     * @return the value of EB_ORDER_DETAIL.PURCHASE_PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public BigDecimal getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.PURCHASE_PRICE
     *
     * @param purchasePrice the value for EB_ORDER_DETAIL.PURCHASE_PRICE
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setPurchasePrice(BigDecimal purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.SIMCARD_SUIT_ID
     *
     * @return the value of EB_ORDER_DETAIL.SIMCARD_SUIT_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public Long getSimcardSuitId() {
        return simcardSuitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.SIMCARD_SUIT_ID
     *
     * @param simcardSuitId the value for EB_ORDER_DETAIL.SIMCARD_SUIT_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setSimcardSuitId(Long simcardSuitId) {
        this.simcardSuitId = simcardSuitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER_DETAIL.SIMCARD_PACKAGE_ID
     *
     * @return the value of EB_ORDER_DETAIL.SIMCARD_PACKAGE_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public String getSimcardPackageId() {
        return simcardPackageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER_DETAIL.SIMCARD_PACKAGE_ID
     *
     * @param simcardPackageId the value for EB_ORDER_DETAIL.SIMCARD_PACKAGE_ID
     *
     * @mbggenerated Wed Nov 21 19:24:04 CST 2018
     */
    public void setSimcardPackageId(String simcardPackageId) {
        this.simcardPackageId = simcardPackageId;
    }
}