package com.xiepanpan.ecps.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class EbOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ORDER_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.PTL_USER_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Long ptlUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.USERNAME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ORDER_NUM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.PAYMENT
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.PAY_PLATFORM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short payPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.DELIVERY
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short delivery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.IS_CONFIRM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short isConfirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ORDER_SUM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private BigDecimal orderSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.SHIP_FEE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private BigDecimal shipFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.IS_PAID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short isPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ORDER_STATE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.PAYMENT_CASH
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short paymentCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.DISTRI_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Long distriId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.DELIVERY_METHOD
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short deliveryMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.PAYMENT_NO
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String paymentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ORDER_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.PAY_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.DEPOSIT_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Date depositTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.SUCCESS_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Date successTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.UPDATE_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.SRV_TYPE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short srvType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.SELF_COLLECT_SITE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String selfCollectSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.SELF_COLLECT_SITE_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Long selfCollectSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.IS_DELETED
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.IS_DISPLAY
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short isDisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.NOTES
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.SHIP_NAME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String shipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.PROVINCE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.CITY
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.DISTRICT
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ZIP_CODE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ADDR
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.PHONE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.PAYABLE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short payable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.COMPANY
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.CONTENTS
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short contents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.IS_CALL
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short isCall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.DELIVERY_NO
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String deliveryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.AREA_CODE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.AREA_NAME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.IS_PRINT
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short isPrint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.CRM_CALLS_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Date crmCallsTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.IS_OFFER_RELEASE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short isOfferRelease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.JOB_NUM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String jobNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ORDER_TYPE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.FIXED_PHONE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String fixedPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ATTACH_FILE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String attachFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.RETURN_TYPE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Long returnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.SECKILL_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Long seckillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ORDER_SOURCE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private Short orderSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ORDER_EXT1
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String orderExt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ORDER_EXT2
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String orderExt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ORDER_EXT3
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String orderExt3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ORDER_EXT4
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String orderExt4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ORDER.ORDER_EXT5
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    private String orderExt5;

    /**
     * 省
     */
    private String provText;

    /**
     * 市
     */
    private String cityText;

    /**
     * 区
     */
    private String distText;

    private List<EbOrderDetail> ebOrderDetailList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ORDER_ID
     *
     * @return the value of EB_ORDER.ORDER_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ORDER_ID
     *
     * @param orderId the value for EB_ORDER.ORDER_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.PTL_USER_ID
     *
     * @return the value of EB_ORDER.PTL_USER_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Long getPtlUserId() {
        return ptlUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.PTL_USER_ID
     *
     * @param ptlUserId the value for EB_ORDER.PTL_USER_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setPtlUserId(Long ptlUserId) {
        this.ptlUserId = ptlUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.USERNAME
     *
     * @return the value of EB_ORDER.USERNAME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.USERNAME
     *
     * @param username the value for EB_ORDER.USERNAME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ORDER_NUM
     *
     * @return the value of EB_ORDER.ORDER_NUM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ORDER_NUM
     *
     * @param orderNum the value for EB_ORDER.ORDER_NUM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.PAYMENT
     *
     * @return the value of EB_ORDER.PAYMENT
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.PAYMENT
     *
     * @param payment the value for EB_ORDER.PAYMENT
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setPayment(Short payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.PAY_PLATFORM
     *
     * @return the value of EB_ORDER.PAY_PLATFORM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getPayPlatform() {
        return payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.PAY_PLATFORM
     *
     * @param payPlatform the value for EB_ORDER.PAY_PLATFORM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setPayPlatform(Short payPlatform) {
        this.payPlatform = payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.DELIVERY
     *
     * @return the value of EB_ORDER.DELIVERY
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getDelivery() {
        return delivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.DELIVERY
     *
     * @param delivery the value for EB_ORDER.DELIVERY
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setDelivery(Short delivery) {
        this.delivery = delivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.IS_CONFIRM
     *
     * @return the value of EB_ORDER.IS_CONFIRM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getIsConfirm() {
        return isConfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.IS_CONFIRM
     *
     * @param isConfirm the value for EB_ORDER.IS_CONFIRM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setIsConfirm(Short isConfirm) {
        this.isConfirm = isConfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ORDER_SUM
     *
     * @return the value of EB_ORDER.ORDER_SUM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public BigDecimal getOrderSum() {
        return orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ORDER_SUM
     *
     * @param orderSum the value for EB_ORDER.ORDER_SUM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setOrderSum(BigDecimal orderSum) {
        this.orderSum = orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.SHIP_FEE
     *
     * @return the value of EB_ORDER.SHIP_FEE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public BigDecimal getShipFee() {
        return shipFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.SHIP_FEE
     *
     * @param shipFee the value for EB_ORDER.SHIP_FEE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setShipFee(BigDecimal shipFee) {
        this.shipFee = shipFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.IS_PAID
     *
     * @return the value of EB_ORDER.IS_PAID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getIsPaid() {
        return isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.IS_PAID
     *
     * @param isPaid the value for EB_ORDER.IS_PAID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setIsPaid(Short isPaid) {
        this.isPaid = isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ORDER_STATE
     *
     * @return the value of EB_ORDER.ORDER_STATE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ORDER_STATE
     *
     * @param orderState the value for EB_ORDER.ORDER_STATE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setOrderState(Short orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.PAYMENT_CASH
     *
     * @return the value of EB_ORDER.PAYMENT_CASH
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getPaymentCash() {
        return paymentCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.PAYMENT_CASH
     *
     * @param paymentCash the value for EB_ORDER.PAYMENT_CASH
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setPaymentCash(Short paymentCash) {
        this.paymentCash = paymentCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.DISTRI_ID
     *
     * @return the value of EB_ORDER.DISTRI_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Long getDistriId() {
        return distriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.DISTRI_ID
     *
     * @param distriId the value for EB_ORDER.DISTRI_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setDistriId(Long distriId) {
        this.distriId = distriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.DELIVERY_METHOD
     *
     * @return the value of EB_ORDER.DELIVERY_METHOD
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getDeliveryMethod() {
        return deliveryMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.DELIVERY_METHOD
     *
     * @param deliveryMethod the value for EB_ORDER.DELIVERY_METHOD
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setDeliveryMethod(Short deliveryMethod) {
        this.deliveryMethod = deliveryMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.PAYMENT_NO
     *
     * @return the value of EB_ORDER.PAYMENT_NO
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getPaymentNo() {
        return paymentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.PAYMENT_NO
     *
     * @param paymentNo the value for EB_ORDER.PAYMENT_NO
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setPaymentNo(String paymentNo) {
        this.paymentNo = paymentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ORDER_TIME
     *
     * @return the value of EB_ORDER.ORDER_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ORDER_TIME
     *
     * @param orderTime the value for EB_ORDER.ORDER_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.PAY_TIME
     *
     * @return the value of EB_ORDER.PAY_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.PAY_TIME
     *
     * @param payTime the value for EB_ORDER.PAY_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.DEPOSIT_TIME
     *
     * @return the value of EB_ORDER.DEPOSIT_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Date getDepositTime() {
        return depositTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.DEPOSIT_TIME
     *
     * @param depositTime the value for EB_ORDER.DEPOSIT_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setDepositTime(Date depositTime) {
        this.depositTime = depositTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.SUCCESS_TIME
     *
     * @return the value of EB_ORDER.SUCCESS_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Date getSuccessTime() {
        return successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.SUCCESS_TIME
     *
     * @param successTime the value for EB_ORDER.SUCCESS_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setSuccessTime(Date successTime) {
        this.successTime = successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.UPDATE_TIME
     *
     * @return the value of EB_ORDER.UPDATE_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.UPDATE_TIME
     *
     * @param updateTime the value for EB_ORDER.UPDATE_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.SRV_TYPE
     *
     * @return the value of EB_ORDER.SRV_TYPE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getSrvType() {
        return srvType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.SRV_TYPE
     *
     * @param srvType the value for EB_ORDER.SRV_TYPE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setSrvType(Short srvType) {
        this.srvType = srvType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.SELF_COLLECT_SITE
     *
     * @return the value of EB_ORDER.SELF_COLLECT_SITE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getSelfCollectSite() {
        return selfCollectSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.SELF_COLLECT_SITE
     *
     * @param selfCollectSite the value for EB_ORDER.SELF_COLLECT_SITE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setSelfCollectSite(String selfCollectSite) {
        this.selfCollectSite = selfCollectSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.SELF_COLLECT_SITE_ID
     *
     * @return the value of EB_ORDER.SELF_COLLECT_SITE_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Long getSelfCollectSiteId() {
        return selfCollectSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.SELF_COLLECT_SITE_ID
     *
     * @param selfCollectSiteId the value for EB_ORDER.SELF_COLLECT_SITE_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setSelfCollectSiteId(Long selfCollectSiteId) {
        this.selfCollectSiteId = selfCollectSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.IS_DELETED
     *
     * @return the value of EB_ORDER.IS_DELETED
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.IS_DELETED
     *
     * @param isDeleted the value for EB_ORDER.IS_DELETED
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.IS_DISPLAY
     *
     * @return the value of EB_ORDER.IS_DISPLAY
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getIsDisplay() {
        return isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.IS_DISPLAY
     *
     * @param isDisplay the value for EB_ORDER.IS_DISPLAY
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setIsDisplay(Short isDisplay) {
        this.isDisplay = isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.NOTES
     *
     * @return the value of EB_ORDER.NOTES
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.NOTES
     *
     * @param notes the value for EB_ORDER.NOTES
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.SHIP_NAME
     *
     * @return the value of EB_ORDER.SHIP_NAME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getShipName() {
        return shipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.SHIP_NAME
     *
     * @param shipName the value for EB_ORDER.SHIP_NAME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setShipName(String shipName) {
        this.shipName = shipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.PROVINCE
     *
     * @return the value of EB_ORDER.PROVINCE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.PROVINCE
     *
     * @param province the value for EB_ORDER.PROVINCE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.CITY
     *
     * @return the value of EB_ORDER.CITY
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.CITY
     *
     * @param city the value for EB_ORDER.CITY
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.DISTRICT
     *
     * @return the value of EB_ORDER.DISTRICT
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.DISTRICT
     *
     * @param district the value for EB_ORDER.DISTRICT
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ZIP_CODE
     *
     * @return the value of EB_ORDER.ZIP_CODE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ZIP_CODE
     *
     * @param zipCode the value for EB_ORDER.ZIP_CODE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ADDR
     *
     * @return the value of EB_ORDER.ADDR
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ADDR
     *
     * @param addr the value for EB_ORDER.ADDR
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.PHONE
     *
     * @return the value of EB_ORDER.PHONE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.PHONE
     *
     * @param phone the value for EB_ORDER.PHONE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.PAYABLE
     *
     * @return the value of EB_ORDER.PAYABLE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getPayable() {
        return payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.PAYABLE
     *
     * @param payable the value for EB_ORDER.PAYABLE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setPayable(Short payable) {
        this.payable = payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.COMPANY
     *
     * @return the value of EB_ORDER.COMPANY
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.COMPANY
     *
     * @param company the value for EB_ORDER.COMPANY
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.CONTENTS
     *
     * @return the value of EB_ORDER.CONTENTS
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.CONTENTS
     *
     * @param contents the value for EB_ORDER.CONTENTS
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setContents(Short contents) {
        this.contents = contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.IS_CALL
     *
     * @return the value of EB_ORDER.IS_CALL
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getIsCall() {
        return isCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.IS_CALL
     *
     * @param isCall the value for EB_ORDER.IS_CALL
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setIsCall(Short isCall) {
        this.isCall = isCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.DELIVERY_NO
     *
     * @return the value of EB_ORDER.DELIVERY_NO
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getDeliveryNo() {
        return deliveryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.DELIVERY_NO
     *
     * @param deliveryNo the value for EB_ORDER.DELIVERY_NO
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setDeliveryNo(String deliveryNo) {
        this.deliveryNo = deliveryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.AREA_CODE
     *
     * @return the value of EB_ORDER.AREA_CODE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.AREA_CODE
     *
     * @param areaCode the value for EB_ORDER.AREA_CODE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.AREA_NAME
     *
     * @return the value of EB_ORDER.AREA_NAME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.AREA_NAME
     *
     * @param areaName the value for EB_ORDER.AREA_NAME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.IS_PRINT
     *
     * @return the value of EB_ORDER.IS_PRINT
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getIsPrint() {
        return isPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.IS_PRINT
     *
     * @param isPrint the value for EB_ORDER.IS_PRINT
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setIsPrint(Short isPrint) {
        this.isPrint = isPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.CRM_CALLS_TIME
     *
     * @return the value of EB_ORDER.CRM_CALLS_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Date getCrmCallsTime() {
        return crmCallsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.CRM_CALLS_TIME
     *
     * @param crmCallsTime the value for EB_ORDER.CRM_CALLS_TIME
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setCrmCallsTime(Date crmCallsTime) {
        this.crmCallsTime = crmCallsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.IS_OFFER_RELEASE
     *
     * @return the value of EB_ORDER.IS_OFFER_RELEASE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getIsOfferRelease() {
        return isOfferRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.IS_OFFER_RELEASE
     *
     * @param isOfferRelease the value for EB_ORDER.IS_OFFER_RELEASE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setIsOfferRelease(Short isOfferRelease) {
        this.isOfferRelease = isOfferRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.JOB_NUM
     *
     * @return the value of EB_ORDER.JOB_NUM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getJobNum() {
        return jobNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.JOB_NUM
     *
     * @param jobNum the value for EB_ORDER.JOB_NUM
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setJobNum(String jobNum) {
        this.jobNum = jobNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ORDER_TYPE
     *
     * @return the value of EB_ORDER.ORDER_TYPE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ORDER_TYPE
     *
     * @param orderType the value for EB_ORDER.ORDER_TYPE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setOrderType(Short orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.FIXED_PHONE
     *
     * @return the value of EB_ORDER.FIXED_PHONE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getFixedPhone() {
        return fixedPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.FIXED_PHONE
     *
     * @param fixedPhone the value for EB_ORDER.FIXED_PHONE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setFixedPhone(String fixedPhone) {
        this.fixedPhone = fixedPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ATTACH_FILE
     *
     * @return the value of EB_ORDER.ATTACH_FILE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getAttachFile() {
        return attachFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ATTACH_FILE
     *
     * @param attachFile the value for EB_ORDER.ATTACH_FILE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setAttachFile(String attachFile) {
        this.attachFile = attachFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.RETURN_TYPE
     *
     * @return the value of EB_ORDER.RETURN_TYPE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Long getReturnType() {
        return returnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.RETURN_TYPE
     *
     * @param returnType the value for EB_ORDER.RETURN_TYPE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setReturnType(Long returnType) {
        this.returnType = returnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.SECKILL_ID
     *
     * @return the value of EB_ORDER.SECKILL_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Long getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.SECKILL_ID
     *
     * @param seckillId the value for EB_ORDER.SECKILL_ID
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setSeckillId(Long seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ORDER_SOURCE
     *
     * @return the value of EB_ORDER.ORDER_SOURCE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public Short getOrderSource() {
        return orderSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ORDER_SOURCE
     *
     * @param orderSource the value for EB_ORDER.ORDER_SOURCE
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setOrderSource(Short orderSource) {
        this.orderSource = orderSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ORDER_EXT1
     *
     * @return the value of EB_ORDER.ORDER_EXT1
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getOrderExt1() {
        return orderExt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ORDER_EXT1
     *
     * @param orderExt1 the value for EB_ORDER.ORDER_EXT1
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setOrderExt1(String orderExt1) {
        this.orderExt1 = orderExt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ORDER_EXT2
     *
     * @return the value of EB_ORDER.ORDER_EXT2
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getOrderExt2() {
        return orderExt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ORDER_EXT2
     *
     * @param orderExt2 the value for EB_ORDER.ORDER_EXT2
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setOrderExt2(String orderExt2) {
        this.orderExt2 = orderExt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ORDER_EXT3
     *
     * @return the value of EB_ORDER.ORDER_EXT3
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getOrderExt3() {
        return orderExt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ORDER_EXT3
     *
     * @param orderExt3 the value for EB_ORDER.ORDER_EXT3
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setOrderExt3(String orderExt3) {
        this.orderExt3 = orderExt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ORDER_EXT4
     *
     * @return the value of EB_ORDER.ORDER_EXT4
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getOrderExt4() {
        return orderExt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ORDER_EXT4
     *
     * @param orderExt4 the value for EB_ORDER.ORDER_EXT4
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setOrderExt4(String orderExt4) {
        this.orderExt4 = orderExt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ORDER.ORDER_EXT5
     *
     * @return the value of EB_ORDER.ORDER_EXT5
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public String getOrderExt5() {
        return orderExt5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ORDER.ORDER_EXT5
     *
     * @param orderExt5 the value for EB_ORDER.ORDER_EXT5
     *
     * @mbggenerated Wed Nov 21 19:21:50 CST 2018
     */
    public void setOrderExt5(String orderExt5) {
        this.orderExt5 = orderExt5;
    }

    public String getProvText() {
        return provText;
    }

    public void setProvText(String provText) {
        this.provText = provText;
    }

    public String getCityText() {
        return cityText;
    }

    public void setCityText(String cityText) {
        this.cityText = cityText;
    }

    public String getDistText() {
        return distText;
    }

    public void setDistText(String distText) {
        this.distText = distText;
    }

    public List<EbOrderDetail> getEbOrderDetailList() {
        return ebOrderDetailList;
    }

    public void setEbOrderDetailList(List<EbOrderDetail> ebOrderDetailList) {
        this.ebOrderDetailList = ebOrderDetailList;
    }
}