package com.xiepanpan.ecps.model;

/**
 * 规格实体类
 */
public class EbSpecValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SPEC_VALUE.SPEC_ID
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    private Long specId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SPEC_VALUE.SKU_ID
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    private Long skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SPEC_VALUE.FEATURE_ID
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    private Long featureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SPEC_VALUE.SPEC_VALUE
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    private String specValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SPEC_VALUE.SPEC_ID
     *
     * @return the value of EB_SPEC_VALUE.SPEC_ID
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public Long getSpecId() {
        return specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SPEC_VALUE.SPEC_ID
     *
     * @param specId the value for EB_SPEC_VALUE.SPEC_ID
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public void setSpecId(Long specId) {
        this.specId = specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SPEC_VALUE.SKU_ID
     *
     * @return the value of EB_SPEC_VALUE.SKU_ID
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SPEC_VALUE.SKU_ID
     *
     * @param skuId the value for EB_SPEC_VALUE.SKU_ID
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SPEC_VALUE.FEATURE_ID
     *
     * @return the value of EB_SPEC_VALUE.FEATURE_ID
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public Long getFeatureId() {
        return featureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SPEC_VALUE.FEATURE_ID
     *
     * @param featureId the value for EB_SPEC_VALUE.FEATURE_ID
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public void setFeatureId(Long featureId) {
        this.featureId = featureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SPEC_VALUE.SPEC_VALUE
     *
     * @return the value of EB_SPEC_VALUE.SPEC_VALUE
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public String getSpecValue() {
        return specValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SPEC_VALUE.SPEC_VALUE
     *
     * @param specValue the value for EB_SPEC_VALUE.SPEC_VALUE
     *
     * @mbggenerated Thu Nov 08 23:32:17 SGT 2018
     */
    public void setSpecValue(String specValue) {
        this.specValue = specValue;
    }
}