package com.xiepanpan.ecps.model;

import java.util.Date;

public class TsPtlUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.PTL_USER_ID
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private Long ptlUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.USERNAME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.GENDER
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private Short gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.PASSWORD
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.NICKNAME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.REAL_NAME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.PHONE
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.RESI_PROV
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String resiProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.RESI_CITY
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String resiCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.RESI_DIST
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String resiDist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.ADDR
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.ZIP_CODE
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private Integer zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.LOGIN_TIME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.STATUS
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.EMAIL
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.GROUP_ID
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.BIRTHDAY
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.QQ_NUM
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String qqNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.MSN_NUM
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String msnNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.CELLPHONE
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String cellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.INTRO_INFO
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private String introInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.LOGIN_COUNT
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private Long loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.REGISTER_TIME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_PTL_USER.IS_MOBILE_CLIENT
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    private Short isMobileClient;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.PTL_USER_ID
     *
     * @return the value of TS_PTL_USER.PTL_USER_ID
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public Long getPtlUserId() {
        return ptlUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.PTL_USER_ID
     *
     * @param ptlUserId the value for TS_PTL_USER.PTL_USER_ID
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setPtlUserId(Long ptlUserId) {
        this.ptlUserId = ptlUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.USERNAME
     *
     * @return the value of TS_PTL_USER.USERNAME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.USERNAME
     *
     * @param username the value for TS_PTL_USER.USERNAME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.GENDER
     *
     * @return the value of TS_PTL_USER.GENDER
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.GENDER
     *
     * @param gender the value for TS_PTL_USER.GENDER
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.PASSWORD
     *
     * @return the value of TS_PTL_USER.PASSWORD
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.PASSWORD
     *
     * @param password the value for TS_PTL_USER.PASSWORD
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.NICKNAME
     *
     * @return the value of TS_PTL_USER.NICKNAME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.NICKNAME
     *
     * @param nickname the value for TS_PTL_USER.NICKNAME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.REAL_NAME
     *
     * @return the value of TS_PTL_USER.REAL_NAME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.REAL_NAME
     *
     * @param realName the value for TS_PTL_USER.REAL_NAME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.PHONE
     *
     * @return the value of TS_PTL_USER.PHONE
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.PHONE
     *
     * @param phone the value for TS_PTL_USER.PHONE
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.RESI_PROV
     *
     * @return the value of TS_PTL_USER.RESI_PROV
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getResiProv() {
        return resiProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.RESI_PROV
     *
     * @param resiProv the value for TS_PTL_USER.RESI_PROV
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setResiProv(String resiProv) {
        this.resiProv = resiProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.RESI_CITY
     *
     * @return the value of TS_PTL_USER.RESI_CITY
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getResiCity() {
        return resiCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.RESI_CITY
     *
     * @param resiCity the value for TS_PTL_USER.RESI_CITY
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setResiCity(String resiCity) {
        this.resiCity = resiCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.RESI_DIST
     *
     * @return the value of TS_PTL_USER.RESI_DIST
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getResiDist() {
        return resiDist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.RESI_DIST
     *
     * @param resiDist the value for TS_PTL_USER.RESI_DIST
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setResiDist(String resiDist) {
        this.resiDist = resiDist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.ADDR
     *
     * @return the value of TS_PTL_USER.ADDR
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.ADDR
     *
     * @param addr the value for TS_PTL_USER.ADDR
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.ZIP_CODE
     *
     * @return the value of TS_PTL_USER.ZIP_CODE
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public Integer getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.ZIP_CODE
     *
     * @param zipCode the value for TS_PTL_USER.ZIP_CODE
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setZipCode(Integer zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.LOGIN_TIME
     *
     * @return the value of TS_PTL_USER.LOGIN_TIME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.LOGIN_TIME
     *
     * @param loginTime the value for TS_PTL_USER.LOGIN_TIME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.STATUS
     *
     * @return the value of TS_PTL_USER.STATUS
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.STATUS
     *
     * @param status the value for TS_PTL_USER.STATUS
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.EMAIL
     *
     * @return the value of TS_PTL_USER.EMAIL
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.EMAIL
     *
     * @param email the value for TS_PTL_USER.EMAIL
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.GROUP_ID
     *
     * @return the value of TS_PTL_USER.GROUP_ID
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.GROUP_ID
     *
     * @param groupId the value for TS_PTL_USER.GROUP_ID
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.BIRTHDAY
     *
     * @return the value of TS_PTL_USER.BIRTHDAY
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.BIRTHDAY
     *
     * @param birthday the value for TS_PTL_USER.BIRTHDAY
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.QQ_NUM
     *
     * @return the value of TS_PTL_USER.QQ_NUM
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getQqNum() {
        return qqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.QQ_NUM
     *
     * @param qqNum the value for TS_PTL_USER.QQ_NUM
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setQqNum(String qqNum) {
        this.qqNum = qqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.MSN_NUM
     *
     * @return the value of TS_PTL_USER.MSN_NUM
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getMsnNum() {
        return msnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.MSN_NUM
     *
     * @param msnNum the value for TS_PTL_USER.MSN_NUM
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setMsnNum(String msnNum) {
        this.msnNum = msnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.CELLPHONE
     *
     * @return the value of TS_PTL_USER.CELLPHONE
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.CELLPHONE
     *
     * @param cellphone the value for TS_PTL_USER.CELLPHONE
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.INTRO_INFO
     *
     * @return the value of TS_PTL_USER.INTRO_INFO
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public String getIntroInfo() {
        return introInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.INTRO_INFO
     *
     * @param introInfo the value for TS_PTL_USER.INTRO_INFO
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setIntroInfo(String introInfo) {
        this.introInfo = introInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.LOGIN_COUNT
     *
     * @return the value of TS_PTL_USER.LOGIN_COUNT
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public Long getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.LOGIN_COUNT
     *
     * @param loginCount the value for TS_PTL_USER.LOGIN_COUNT
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setLoginCount(Long loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.REGISTER_TIME
     *
     * @return the value of TS_PTL_USER.REGISTER_TIME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.REGISTER_TIME
     *
     * @param registerTime the value for TS_PTL_USER.REGISTER_TIME
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_PTL_USER.IS_MOBILE_CLIENT
     *
     * @return the value of TS_PTL_USER.IS_MOBILE_CLIENT
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public Short getIsMobileClient() {
        return isMobileClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_PTL_USER.IS_MOBILE_CLIENT
     *
     * @param isMobileClient the value for TS_PTL_USER.IS_MOBILE_CLIENT
     *
     * @mbggenerated Wed Nov 14 18:58:36 CST 2018
     */
    public void setIsMobileClient(Short isMobileClient) {
        this.isMobileClient = isMobileClient;
    }
}